apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: busybox
  name: busybox
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - ../../configs/staging/values-common.yaml
      - ../../configs/staging/values-busybox.yaml
    path: charts/worker
    repoURL: https://github.com/Yagora/busybox-argocd
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
