env: staging
name: busybox

image:
  name: "busybox"
  command:
    command: ["sh", "-c"]
    arguments: ["echo $message && tail -f /dev/null"]
  env:
    - name: message
      value: "Hola iexec!"

autoscaling:
  enabled: true
  minReplicas: 2
