name: busybox

image:
  name: "busybox"
  command:
    command: ["sh", "-c"]
    arguments: ["echo $lastname && tail -f /dev/null"]
  env:
    - name: lastname
      value: "hello patrick"

autoscaling:
  minReplicas: 1
