---
{{- if .Values.cm }}
{{ $name := .Values.name }}
{{ $labels := .Values.name }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  {{ with $labels }}
  labels:
    app: {{ toYaml . | indent 4 }}
  {{ end }}
data:
{{ range .Values.cm }}
  {{.name}}: |
{{ .data | indent 4 }}
{{ end }}
{{end}}
