apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "webapp.topologySpreadConstraints" . | nindent 6 }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        - name: main
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.image.command }}
          command: {{ .Values.image.command.command | toYaml | nindent 12 }}
          args: {{ .Values.image.command.arguments | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.cm }}
          volumeMounts:
            {{- $name := .Values.name }}
            {{- range .Values.cm }}
            - name: {{ $name }}
              mountPath: {{ .path }}
              subPath: {{ .name }}
            {{- end }}
          {{- end }}
      {{- if .Values.cm }}
      {{- $name := .Values.name }}
      volumes:
        {{- range .Values.cm }}
        - name: {{ $name }}
          configMap:
            name: {{ $name }}
        {{- end }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
