name: default
env: dev

image:
  name: nginx
  tag: "latest"
  pullPolicy: IfNotPresent
  env: []

serviceAccountName: default
terminationGracePeriodSeconds: 2
# If autoscaling is enabled, the replicaCount is ignored
replicaCount: 1

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  cooldownPeriod: 10 # How many seconds should we wait for downscale. If minReplicas != 0 this value will be 5minutes
  queues:
    - queueURL:
      queueLength: 5 # Target value for queue length passed to the scaler. Example: if one pod can handle 10 messages, set the queue length target to 10. If the actual messages in the SQS Queue is 30, the scaler scales to 3 pods. (default: 5)
      azureRegion: "eu-west-1"
nodeSelector: {}

cm:
  - name: conf
    path: /app.txt
    data: hello
